/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bookshop;

import books.addBook;
import books.allbooks;
import books.expensebook;
import books.rentedbooks;
import books.soldbooks;

/**
 *
 * @author brevin
 */
public class books extends javax.swing.JInternalFrame {

    /**
     * Creates new form allOrdersTable
     */
    public books() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addbook = new javax.swing.JButton();
        soldbooks = new javax.swing.JButton();
        allbooks = new javax.swing.JButton();
        rentedbooks = new javax.swing.JButton();
        expense = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1185, 695));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        addbook.setBackground(new java.awt.Color(51, 51, 255));
        addbook.setForeground(new java.awt.Color(255, 255, 255));
        addbook.setText("Add Book");
        addbook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        addbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });

        soldbooks.setBackground(new java.awt.Color(51, 51, 255));
        soldbooks.setForeground(new java.awt.Color(255, 255, 255));
        soldbooks.setText("Sold Books");
        soldbooks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        soldbooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soldbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldbooksActionPerformed(evt);
            }
        });

        allbooks.setBackground(new java.awt.Color(51, 51, 255));
        allbooks.setForeground(new java.awt.Color(255, 255, 255));
        allbooks.setText("All Books");
        allbooks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        allbooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        allbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allbooksActionPerformed(evt);
            }
        });

        rentedbooks.setBackground(new java.awt.Color(51, 51, 255));
        rentedbooks.setForeground(new java.awt.Color(255, 255, 255));
        rentedbooks.setText("Rented Books");
        rentedbooks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        rentedbooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rentedbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentedbooksActionPerformed(evt);
            }
        });

        expense.setBackground(new java.awt.Color(51, 51, 255));
        expense.setForeground(new java.awt.Color(255, 255, 255));
        expense.setText("Expense");
        expense.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        expense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(allbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(soldbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(rentedbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(expense, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soldbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentedbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        addBook added = new addBook();
        desktop.add(added);
        added.setVisible(true);
        
    }//GEN-LAST:event_addbookActionPerformed

    private void soldbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldbooksActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        soldbooks sdb = new soldbooks();
        desktop.add(sdb);
        sdb.setVisible(true);
        
    }//GEN-LAST:event_soldbooksActionPerformed

    private void allbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allbooksActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        allbooks all = new allbooks();
        desktop.add(all);
        all.setVisible(true);
        
    }//GEN-LAST:event_allbooksActionPerformed

    private void rentedbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentedbooksActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        rentedbooks rdb = new rentedbooks();
        desktop.add(rdb);
        rdb.setVisible(true);
        
    }//GEN-LAST:event_rentedbooksActionPerformed

    private void expenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        expensebook expenses = new expensebook();
        desktop.add(expenses);
        expenses.show();
        
    }//GEN-LAST:event_expenseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbook;
    private javax.swing.JButton allbooks;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton expense;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rentedbooks;
    private javax.swing.JButton soldbooks;
    // End of variables declaration//GEN-END:variables
}
