/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bookshop;

import employees.addemployee;
import employees.addleave;
import employees.allemployees;
import employees.attendences;
import employees.leaves;
import employees.shifts;
import oders.press_order;

/**
 *
 * @author brevin
 */
public class employees extends javax.swing.JInternalFrame {

    /**
     * Creates new form allOrdersTable
     */
    public employees() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employee = new javax.swing.JButton();
        leave = new javax.swing.JButton();
        addEmployee = new javax.swing.JButton();
        addLeave = new javax.swing.JButton();
        attendence = new javax.swing.JButton();
        shifts = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1185, 695));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        employee.setBackground(new java.awt.Color(51, 51, 255));
        employee.setForeground(new java.awt.Color(255, 255, 255));
        employee.setText("Employees");
        employee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        leave.setBackground(new java.awt.Color(51, 51, 255));
        leave.setForeground(new java.awt.Color(255, 255, 255));
        leave.setText("Leaves");
        leave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        leave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });

        addEmployee.setBackground(new java.awt.Color(51, 51, 255));
        addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        addEmployee.setText("Add Employee");
        addEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        addEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });

        addLeave.setBackground(new java.awt.Color(51, 51, 255));
        addLeave.setForeground(new java.awt.Color(255, 255, 255));
        addLeave.setText("Add leave");
        addLeave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        addLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLeaveActionPerformed(evt);
            }
        });

        attendence.setBackground(new java.awt.Color(51, 51, 255));
        attendence.setForeground(new java.awt.Color(255, 255, 255));
        attendence.setText("Attendence");
        attendence.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        attendence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceActionPerformed(evt);
            }
        });

        shifts.setBackground(new java.awt.Color(51, 51, 255));
        shifts.setForeground(new java.awt.Color(255, 255, 255));
        shifts.setText("Shifts");
        shifts.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));
        shifts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shifts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(addLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(shifts, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shifts, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        allemployees all = new allemployees();
        desktop.add(all);
        all.show();
        
    }//GEN-LAST:event_employeeActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        leaves leav = new leaves();
        desktop.add(leav);
        leav.show();
        
    }//GEN-LAST:event_leaveActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        addemployee addE = new addemployee();
        desktop.add(addE);
        addE.show();
        
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void addLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLeaveActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        addleave addL = new addleave();
        desktop.add(addL);
        addL.show();
        
    }//GEN-LAST:event_addLeaveActionPerformed

    private void attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        attendences attend = new attendences();
        desktop.add(attend);
        attend.show();
        
    }//GEN-LAST:event_attendenceActionPerformed

    private void shiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftsActionPerformed
        
        desktop.removeAll();
        desktop.repaint();
        shifts shift = new shifts();
        desktop.add(shift);
        shift.show();
        
    }//GEN-LAST:event_shiftsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployee;
    private javax.swing.JButton addLeave;
    private javax.swing.JButton attendence;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton employee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leave;
    private javax.swing.JButton shifts;
    // End of variables declaration//GEN-END:variables
}
